build-job:
  stage: build
  tags:
    - docker
  script:
    - echo "Build for product-shop"
    - apt install docker-compose-plugin
    - ./gradlew clean build -x test
  image: gradle:8.10.2-jdk21

test-job:
  stage: test
  tags:
    - docker
  script:
    - echo "Test for product-shop"
    - apt install docker-compose-plugin
    - ./gradlew test
  image: gradle:8.10.2-jdk21
