build-job:
  stage: build
  tags:
    - docker
  script:
    - echo "Build for product-shop"
    - ./gradlew clean build -x test
  image: docker:27.3.1-cli

test-job:
  stage: test
  tags:
    - docker
  script:
    - echo "Test for product-shop"
    - ./gradlew test
  image: docker:27.3.1-cli
