build-job:
  stage: build
  tags:
    - docker
  script:
    - echo "Build for product-shop"
    - ./gradlew clean build -x test
  image: gradle:8.10.2-jdk21-alpine

test-job:
  stage: test
  tags:
    - docker
  script:
    - echo "Test for product-shop"
    - apk update
    - apk add docker-compose
    - docker-compose version
    - ./gradlew test
  image: gradle:8.10.2-jdk21-alpine
