#build-job:
#  stage: build
#  tags:
#    - docker
#  script:
#    - echo "Build for product-shop"
#    - ./gradlew clean build -x test
#  image: gradle:8.10.2-jdk21-alpine

test-job:
  stage: test
  tags:
    - docker
  script:
    - echo "Test for product-shop"
    - apt-get update
    - apk add docker-compose
    - apt-get install docker-compose-plugin
    - docker-compose version
    - docker-compose -f ./src/test/resources/test_cluster/docker-compose.yml up --force-recreate  -V
    - ./gradlew test
    - docker-compose -f ./src/test/resources/test_cluster/docker-compose.yml down
  image: gradle:8.10.2-jdk21-jammy
