services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

build_ui-job:
  stage: build
  tags:
    - docker_version_2
  script:
    - unset DOCKER_HOST
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -f Dockerfile -t front .

test_ui-job:
  stage: test
  tags:
    - docker_version_2
  script:
    - unset DOCKER_HOST
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker run --rm front
    - cd front
    - python -m unittest test_ui.py

build-job:
  stage: build
  tags:
    - docker_version_2
  script:
    - echo "Build for product-shop"
    - ./gradlew clean build -x test
  image: gradle:8.10.2-jdk21-alpine

test-job:
  stage: test
  tags:
    - docker_version_2
  script:
    - echo "Test for product-shop"
    - ./gradlew test
  image: gradle:8.10.2-jdk21-alpine
