stages:
  - sonar-scan
  - build
  - test


services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

build_ui-job:
  stage: build
  tags:
    - docker_version_2
  script:
    - unset DOCKER_HOST
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -f ./front/Dockerfile -t front .

test_ui-job:
  stage: test
  tags:
    - docker_version_2
  script:
    - unset DOCKER_HOST
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker run --rm -w /app/front front python -m unittest test_ui.py

build-job:
  stage: build
  tags:
    - docker_version_2
  script:
    - echo "Build for product-shop"
    - ./gradlew clean build -x test
  image: gradle:8.10.2-jdk21-alpine

test-job:
  stage: test
  tags:
    - docker_version_2
  script:
    - echo "Test for product-shop"
    - ./gradlew test
  image: gradle:8.10.2-jdk21-alpine

sonarqube-check:
  stage: sonar-scan
  tags:
    - docker_version_2
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache test
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true

