build-job:
  stage: build
  tags:
    - docker
  script:
    - echo "Build for product-shop"
    - docker-compose version
    - ./gradlew clean build -x test
  image: gradle:8.10.2-jdk21

test-job-0:
  stage: build
  tags:
    - docker
  script:
    - echo "Build for product-shop"
    - docker-compose version
    - ./gradlew clean build -x test
  image: docker:27.3.1-cli

test-job:
  stage: test
  tags:
    - docker
  script:
    - echo "Test for product-shop"
    - ./gradlew test
  image: gradle:8.10.2-jdk21
