build_ui-job:
  stage: build
  image: docker:latest
  tags:
    - docker_v2
  script:
    - docker build -f Dockerfile -t front .

test_ui-job:
  stage: test
  image: docker:latest
  tags:
    - docker_v2
  script:
    - docker run -rm front
    - cd front
    - python -m unittest test_ui.py

build-job:
  stage: build
  tags:
    - docker_v2
  script:
    - echo "Build for product-shop"
    - ./gradlew clean build -x test
  image: gradle:8.10.2-jdk21-alpine

test-job:
  stage: test
  tags:
    - docker_v2
  script:
    - echo "Test for product-shop"
    - ./gradlew test
  image: gradle:8.10.2-jdk21-alpine

# TODO: Тест падает, поскольку мне не поднять контейнер с постгрес через docker-compose