openapi: 3.0.0
info:
  title: Product Shop Front API
  version: 1.0.0
servers:
- url: https://d5djobj4r6eaesi3l94c.4b4k4pg5.apigw.yandexcloud.net
paths:
  /:
    get:
      summary: Access the frontend application
      operationId: getFrontend
      responses:
        '200':
          description: Successful response
          content:
            text/html:
              schema:
                type: string
      x-yc-apigateway-integration:
        type: http
        http_method: GET
        url: http://158.160.143.127:8001
        timeout: 30s
  /hello:
    get:
      summary: Say hello
      operationId: hello
      parameters:
        - name: user
          in: query
          description: User name to appear in greetings
          required: false
          schema:
            type: string
            default: 'world'
      responses:
        '200':
          description: Greeting
          content:
            'text/plain':
                schema:
                  type: "string"
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Content-Type': "text/plain"
        content:
          'text/plain': "Hello, {user}!\n"
