apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: plaintext
    targetPort: 8001
  # Selector Kubernetes labels used in the pod template when creating the Deployment object.
  selector:
    io.kompose.service: product-shop-front
