apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: product-shop-front
  name: product-shop-front
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: product-shop-front
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: product-shop-front
    spec:
      containers:
        - env:
            - name: BACKEND_URL
            #  TODO Поправить
              value: http://product-shop-back:8080/
          image: levs2001/lr-product-shop-front:0.0.7-pl
          name: product-shop-front
          ports:
            - containerPort: 8001
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: "1073741824"
            requests:
              cpu: "250m"
              memory: "1073741824"
      restartPolicy: Always
