apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: product-shop-front
  name: product-shop-front
spec:
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8001
      
  selector:
    io.kompose.service: product-shop-front
